### PR TITLE
add Mapbox service

### LINKED ISSUE #71: Add support for Mapbox service
Following #62 , I have implemented Mapbox rebased on `reverse-geocoding` branch.

- Docs: https://docs.mapbox.com/api/search/geocoding/

- Playground: https://docs.mapbox.com/playground/

See the checklist below:

<details>

## Data
- [x]  `data-raw/api_reference.R` updated
- [x]  Modify `R/data.R`

## Sandbox
- [x]  Added `sandbox/query_debugging/mapbox_test.R `
- [x]  Added `sandbox/reverse_queries/mapbox_reverse.R`

## Code
- [x]  `R/utils.R` - Utils added for Mapbox
- [x]  `R/query_factory.R` updated
- [x]  `R/geo_methods.R` updated
- [x]  `R/geo.R` updated
- [x]  `R/reverse_geo.R` updated

## Testing
- [x]  `testthat` test added
- [x]  Modify `regression_testing.Rmd`
- [x]  Run tests included in <https://github.com/jessecambon/tidygeocoder/blob/master/cran-comments.md>

Some Notes not related with the PR itself:

```r
#> * checking CRAN incoming feasibility ... NOTE
#> Version contains large components (1.0.2.9000)
```

And this:

```
Found the following (possibly) invalid URLs:
  URL: https://osm.org/copyright (moved to https://www.openstreetmap.org/copyright)
    From: README.md
    Status: 200
    Message: OK
```

I checked and that url is generated by the response of the `reverse_geocode` on the README (see table on https://github.com/dieghernan/tidygeocoder/blob/master/README.md#usage), so not related with the package.

## Misc
- [x] Update README

</details>

There are two additional topics about which I would like to gather your feedback,

## Integrate Github Action

Github Actions can run `R CMD CHECK`  on a package repo over different platforms and R versions. I use this on my packages, you can see more on https://github.com/r-lib/actions/blob/master/examples/README.md

I included my version while developing. This Github Action would run regularly once a week and after every commit/PR on branchs `master` or `main`,, checks are performed on devel, release, oldrel on Linux, macOS and Windows (as CRAN):
https://github.com/dieghernan/tidygeocoder/actions/runs/620783144

**Before removing it I just wanted to check if you would like to integrate this on your repo.**

## About batch geocoding

This is possible on Mapbox but under the commercial endpoint `mapbox.places-permanent`

https://docs.mapbox.com/api/search/geocoding/#batch-geocoding

I do not have that kind of access, so I didn't include it. I asked Mapbox Team if there is any way I can get a limited dev account for checking, I would let you know.

**What I can do if this is strictly required** is to include the capability using a mock answer of the API as example ([see here](https://github.com/mapbox/MapboxGeocoder.swift/tree/main/Tests/MapboxGeocoderTests/fixtures)), but I won't be able to check it if I don't get a permanent API key (maybe someone with that kind of key could help, @maxachis¿?).

Regards

### PR DESCRIPTION
**Pull request by dieghernan**
close #71 

I also fixed a typo on an example, as it made my checls to fail. https://github.com/jessecambon/tidygeocoder/commit/a70a1967dfbe02d02d406c1c7ff742e37e04b078

On draft mode until I get some feedback

### CODE REVIEW

**Comment by dieghernan** [comment]
Reverse geocoding #66 included for Mapbox

**Comment by jessecambon** [comment]
Hi @dieghernan this looks good, thanks for the PR. I'll pull it in and do some testing this weekend. You probably already tried this, but I'm curious if there is a way to leave the addresses in the parameter list (instead of putting them into the api url).

**Comment by dieghernan** [comment]
For reference, the call should be:

https://docs.mapbox.com/api/search/geocoding/#forward-geocoding
```
/geocoding/v5/{endpoint}/{search_text}.json

```

What I saw is that leaving address into params I got something like:

```
/geocoding/v5/{endpoint}.json&q={search_text}

```

Thas obviously is not valid. I don't know if {httr} has a way to do that, and as I am not an expert I just decided to do what I did, that I admit is a bit sloppy.

@jessecambon  One thing more, is it ok if I add myself as ctb on the DESCRIPTION? Many thanks

**Comment by dieghernan** [comment]
Close #71

**Review by jessecambon — APPROVED** [review]

**Pull request merged**
