### PR TITLE
add OpenCage service

### LINKED ISSUE #67: Add support for OpenCage service
* [Website](https://opencagedata.com/)
* [How to Write a SDK](https://opencagedata.com/guides/how-to-write-an-sdk-for-the-opencage-api)
* [API Documentation](https://opencagedata.com/api)

### PR DESCRIPTION
**Pull request by dpprdan**
This adds support for OpenCage to {tidygeocoder}, closes #67.

I followed #62, which should be visible from my commits. Let me know if I forgot/you'd like me to add something.

I am the new maintainer of {[opencage](https://docs.ropensci.org/opencage/)} BTW. 👋🏻

### CODE REVIEW

**Comment by freyfogle** [comment]
Well done, Daniel!

**Comment by dpprdan** [comment]
@jessecambon I only added those API parameters to `api_parameter_reference` for which there is an applicable `generic_name`, i.e. a function attribute in `geo()`. 
What is the idea behind those parameters that have `generic_name = NA`? Should I add all of OpenCage's other parameters there, so one has an overview of what could be used with `geo(custom_query)`?

**Comment by jessecambon** [comment]
Thanks @dpprdan! I haven't pulled your code in for testing yet, but your commits look good. No need to add all of OpenCage's parameters - I have a few specific parameters in `api_parameter_reference` for the Census geocoder because they are required (atleast for some queries). Outside of that, I've opted to only include parameters that correspond to a "generic" parameter. People can refer to each service's API documentation to see which parameters are available with the `custom_query` passthrough.

**Comment by jessecambon** [comment]
@dpprdan I pulled in your code and everything looks good. Good work on this. It's in the master branch now and will be included in the next CRAN release. I added you as an author in the DESCRIPTION file. Let me know if you have an email address you want me to add to your author entry.

**Comment by freyfogle** [comment]
well done, gentlemen. Well done indeed

**Pull request merged**
